version: '3.9'

services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      
  guacactings:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    ports:
      - "8080:5191"
    volumes:
      - ./:/app
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
    command: >
      bash -c "
        cd /app
        dotnet restore
        dotnet build
        dotnet run --urls http://0.0.0.0:5191
      "