version: '3.9'

services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
  
  guacactings:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    ports:
      - "8080:5191"
    volumes:
      - ./:/app
    environment:
      - ACCEPT_EULA=Y
      - ASPNETCORE_URLS=http://0.0.0.0:5191
      - ASPNETCORE_ENVIRONMENT=Production
    command: >
      bash -c "
        cd /app
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output /app/publish
        dotnet tool install --global dotnet-ef --version 8.0.0-preview.2.23128.3
        /root/.dotnet/tools/dotnet-ef database update
        dotnet /app/publish/guacactings.dll
      "
